import { 
  Belleza, 
  Inter, 
  Chivo, 
  Bitcount_Prop_Single,
  Bitcount_Prop_Double, 
  Plus_Jakarta_Sans,
  Pinyon_Script
} from "next/font/google";
import "./globals.css";

const belleza = Belleza({
  variable: "--font-belleza",
  subsets: ["latin"],
  weight: ["400"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const chivoRegular = Chivo({
  variable: "--font-chivo-regular",
  subsets: ["latin"],
  weight: "400"
});

const bitcountSingle = Bitcount_Prop_Double({
  variable: "--font-bitcount-single",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const bitcountDouble = Bitcount_Prop_Single({
  variable: "--font-bitcount-double",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: [ "200", "300", "400", "500", "600", "700", "800" ],
});

const pinyonScript = Pinyon_Script({
  variable: "--font-pinyon-script",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${belleza.variable} 
          ${inter.variable} 
          ${chivoRegular.variable}
          ${bitcountSingle.variable}
          ${bitcountDouble.variable}
          ${plusJakartaSans.variable}
          ${pinyonScript.variable}
          antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
